services:
  camera:
    build:
      ./camera
    tty: true
    stdin_open: true
    environment:
      - CAMERA_TEMP_DIR=${CAMERA_TEMP_DIR}
    volumes:
      - ./data:/data
    privileged: true
    mem_limit: 8g

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./db:/data/db
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: ${MONGODB_URL}
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password

  