services:
  camera:
    container_name: camera
    build:
      ./camera
    tty: true
    stdin_open: true
    environment:
      - CAMERA_TEMP_DIR=${CAMERA_TEMP_DIR}
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=${XAUTH}
    volumes:
      - ./data:/data
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTH}:${XAUTH}:rw
    privileged: true
    develop:
      watch:
        - path: ./camera
          action: sync
          target: /

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./db:/data/db
    ports:
      - 27017:27017

  mongo-express:
    container_name: mongo-webserver
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: ${MONGODB_URL}
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    depends_on:
      - mongo

  processor:
    container_name: processor
    build: ./processor
    environment:
      - DATA_PATH=${CAMERA_TEMP_DIR}
      - DEEPFACE_MONGO_URI=${MONGODB_URL}
    depends_on:
      - camera
      - mongo
    volumes:
      - ./data:/opt/spark/work-dir/data
    ports:
      - 4040:4040
    develop:
      watch:
        - path: ./processor
          action: sync+restart
          target: /opt/spark/work-dir
    mem_limit: 8g
